---
functional:
- Разработка интерфейса магазина с просмотром, фильтрацией товаров и добавлением их в корзину
- Возможность поиска товаров по ключевому слову или категории
- Возможность фильтрации товаров
- SPA приложение, которое не перезагружает страницу
- Возможность просмотра каталога товаров с постраничным выводом
- Вывод информации о товаре на странице товара и в каталоге: название, рейтинг, цена со скидкой и без
- Возможность добавления товара в корзину и просмотра содержимого корзины
- Возможность удаления товара из корзины
- Возможность оформления заказа и перехода на страницу оплаты
non-functional:
- Адаптивная верстка для удобства использования на мобильных устройствах
- Оптимизация скорости работы сайта
- Безопасность и защита данных пользователя
- Совместимость с последними версиями браузеров
- Обработка большого количества трафика
implicit:
- Интуитивно понятный интерфейс для простоты использования
- Удобство нахождения нужных товаров для повышения удовлетворенности пользователей.
